version: '3'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=your_secure_password
      - N8N_WEBHOOK_TUNNEL_URL=https://your-custom-domain.com
    volumes:
      - ./n8n_data:/home/node/.n8n
